# Generated by Django 3.2.5 on 2022-04-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aiinfo_default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default='', max_length=200)),
                ('default_airec', models.IntegerField(default=-1)),
                ('default_aiconf', models.IntegerField(default=-1)),
                ('default_aieof', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='aipreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(default='', max_length=1000)),
                ('condition', models.CharField(default='', max_length=1000)),
                ('pred', models.DecimalField(decimal_places=3, max_digits=5)),
                ('bin_pred', models.IntegerField(default=-1)),
                ('round_pred', models.IntegerField(default=-1)),
                ('y', models.IntegerField(default=-1)),
                ('condition_short', models.CharField(default='', max_length=1000)),
                ('grouping', models.CharField(default='', max_length=1000)),
                ('accuracy_x_condition_x_binpred', models.IntegerField(default=-1)),
                ('round_accuracy_x_condition_x_binpred', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default='', max_length=200)),
                ('exp_stage', models.IntegerField(default=-1)),
                ('exp_aipresence', models.IntegerField(default=-1)),
                ('image_order', models.IntegerField(default=-1)),
                ('diag_condname', models.CharField(default='', max_length=10)),
                ('diag_condpresent', models.CharField(default='', max_length=10)),
                ('diag_lklpresent', models.IntegerField(default=-1)),
                ('diag_secop', models.CharField(default='', max_length=10)),
                ('diag_aifocustime', models.CharField(default='', max_length=10, null=True)),
                ('diag_qaifocus', models.CharField(default='', max_length=10, null=True)),
                ('diag_aiconftime', models.CharField(default='', max_length=10, null=True)),
                ('diag_aieoftime', models.CharField(default='', max_length=10, null=True)),
                ('diag_airectime', models.CharField(max_length=10, null=True)),
                ('time_completed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='participant_exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default='', max_length=200)),
                ('participant_numeric_id', models.IntegerField(default='-1')),
                ('email', models.EmailField(default='', max_length=1000)),
                ('experience', models.IntegerField(default=-1, help_text='Experience: 1 with experience, 0 otherwise')),
                ('exp_stage', models.IntegerField(default=-1, help_text='Day of experiment')),
                ('exp_workflow', models.IntegerField(default=-1, help_text='Workflow: 1 one-step prediction, 0 two-step prediction')),
                ('exp_group', models.IntegerField(default=-1, help_text='Group assignment')),
                ('image_id', models.CharField(default=-1, max_length=1000)),
                ('image_order', models.IntegerField(default=-1)),
                ('exp_aism', models.IntegerField(default=-1)),
                ('exp_aieof', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='participant_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default='', max_length=200)),
                ('participant_numeric_id', models.IntegerField(default='-1')),
                ('state', models.CharField(default='', max_length=200)),
                ('experience', models.IntegerField(default=-1, help_text='Experience: 1 with experience, 0 otherwise')),
                ('exp_workflow', models.IntegerField(default=-1, help_text='Workflow: 1 one-step prediction, 0 two-step prediction')),
                ('exp_group', models.IntegerField(default=-1, help_text='Group assignment')),
            ],
        ),
        migrations.CreateModel(
            name='participant_stage_completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default='', max_length=200)),
                ('exp_stage', models.IntegerField(default=-1, help_text='Day of experiment')),
            ],
        ),
        migrations.CreateModel(
            name='survey_aiuseful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default='', max_length=200)),
                ('exp_stage', models.IntegerField(default=-1)),
                ('image_order', models.IntegerField(default=-1)),
                ('aiuseful', models.CharField(default='', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='survey_responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default='', max_length=200)),
                ('exp_stage', models.IntegerField(default='-1')),
                ('workload_demanding', models.TextField(default='')),
                ('workload_frustrating', models.TextField(default='')),
                ('confidence_increase', models.TextField(default='')),
                ('usefulness_quickly', models.TextField(default='')),
                ('usefulness_accuracy', models.TextField(default='')),
                ('confidence_aifocus', models.TextField(default='', null=True)),
                ('usefulness_eof', models.TextField(default='', null=True)),
                ('usefulness_whenmosthelpful', models.TextField(default='')),
                ('usefulness_whenleasthelpful', models.TextField(default='')),
                ('trust_whenpresent', models.TextField(default='')),
                ('trust_whennotpresent', models.TextField(default='')),
                ('trust_howfinalrec', models.TextField(default='')),
                ('trust_understandmistakes', models.TextField(default='')),
                ('trust_errorsmade', models.TextField(default='')),
                ('trust_whentrustai', models.TextField(default='')),
                ('futureuse_daily', models.TextField(default='')),
                ('elaborate', models.TextField(default='')),
                ('rank_usefulness_confidence', models.TextField(default='', null=True)),
                ('rank_usefulness_aifocus', models.TextField(default='', null=True)),
                ('rank_usefulness_eof', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='timepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default='', max_length=200)),
                ('exp_stage', models.IntegerField(default='-1')),
                ('page', models.CharField(default='', max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
